#!/usr/bin/env bash
notify() {
  notify-send -t 3000 -a system-notify "$1"
  echo "$1"
}

attach_or_create_session() {
  local session_name=$1
  # Function to kill and attach to a session
  kill_and_attach() {
    zellij kill-session "$session_name"
    zellij -s "$session_name" --layout "$session_name" || zellij -s "$session_name"
  }

  attach_session() {
    notify "attempting to attach to $session_name..."
    zellij attach "$session_name"
  }

  # Check if the session exists
  if zellij list-sessions -s | grep -q "$session_name"; then
    notify "Session '$session_name' already exists."

    action=$(gum choose "Attach" "Kill and Attach" "Exit")

    case $action in
    "Attach")
      attach_session
      ;;
    "Kill and Attach")
      kill_and_attach
      ;;
    "Exit")
      echo "Exiting without action"
      exit 0
      ;;
    esac
  else
    notify "$session_name doesnt exist. Creating now..."
    zellij -s "$session_name" --layout "$session_name" || zellij -s "$session_name"
  fi
}

# Main function
main() {
  local session_name="$1"
  attach_or_create_session "$session_name"
}

main "$@"
