#!/usr/bin/env bash
notify() {
  notify-send -t 3000 -a zellij-menu "$@"
}

notify_error() {
  TITLE=${2:-"Zellij Menu"}
  MESSAGE=${1:-"Unknown error"}
  notify -u critical "$TITLE" "$MESSAGE"
}

notify_exit() {
  notify_error "$1"
  echo "$1"
  exit 2
}

gum_zjm() {

  gum_input_session_name() {
    gum input --header="Session name:" --placeholder="Enter session name"
  }

  gum_choose_action() {
    gum choose --header="Session '$1' already exists, what would you like to do?" "Attach" "Kill and Create" "Exit"
  }

  gum_layout_picker() {
    choice=$(gum choose --header="What layout would you like to use?" "Default" "Choose" "Exit")
    case $choice in
    "Default")
      echo ""
      ;;
    "Choose")
      layout=$(find ~/.config/zellij/layouts . -name "*.kdl" | sed 's|.*/||; s/\.kdl$//' | gum choose --header="What layout would you like to use?")
      if [ -z "$layout" ]; then
        echo "NO_LAYOUT_CHOSEN"
      else
        echo "$layout"
      fi
      ;;
    "Exit")
      echo "exiting..." &
      exit 0
      ;;
    *)
      echo "exiting..." &
      exit 0
      ;;
    esac
  }

  local session_name=$1

  if [ -z "$session_name" ]; then
    session_name="$(gum input --header="Session name:" --placeholder="")"
    if [ -z "$session_name" ]; then
      echo "No session name provided, exiting..." &
      exit 0
    fi
  fi

  # Check if the session exists
  if zellij list-sessions -s | grep -q "$session_name"; then
    notify "Session '$session_name' already exists."

    action=$(gum choose "Attach" "Kill and Create" "Exit")

    case $action in
    "Attach")
      zellij attach "$session_name"
      echo "attached to $session_name" &
      exit 0
      ;;
    "Kill and Create")
      zellij kill-session "$session_name"
      ;;
    "Exit")
      echo "Exiting without action" &
      exit 0
      ;;
    *)
      echo "Exiting without action" &
      exit 0
      ;;
    esac
  fi
  layout=$(gum_layout_picker)
  if [ "$layout" == "NO_LAYOUT_CHOSEN" ]; then
    echo "No layout selected, exiting..."
    exit 0
  elif [ -n "$layout" ]; then
    zellij -s "$session_name" --layout "$layout"
  else
    zellij -s "$session_name"
  fi
}

dmenu_zjm() {
  sessions=$(zellij ls -s | tr ' ' '\n')
  selection=$(echo -e "$sessions\nNew session" | rofi -dmenu -i -mesg "Select Zellij session:")

  case $selection in
  "New session")
    # Prompt for new session name
    new_session_name=$(rofi -dmenu -mesg "Enter new session name:")

    # Get layout for zellij layouts directory
    layouts=$(find ~/.config/zellij/layouts . -name "*.kdl" | sed 's|.*/||; s/\.kdl$//' | tr ' ' '\n')
    choose_layout=$(echo -e "$layouts" | rofi -dmenu -i -mesg "Select Layout") || notify_exit "No layout chosen, exiting..."

    if [[ -n $new_session_name ]]; then
      zellij -s "$new_session_name" --layout "$choose_layout"
    fi
    ;;
  "")
    notify_exit "No selection made, exiting..."
    ;;
  *)
    zellij attach "$selection"
    ;;
  esac

}

# Main function
main() {
  action="$1"

  case "$action" in
  --dmenu)
    shift
    dmenu_zjm
    ;;
  *)
    gum_zjm "$@"
    ;;
  esac
}

main "$@"
