#!/usr/bin/env bash
zellij_cmd() {
  if [ -t 0 ]; then
    zellij "$@"
  else
    $TERM -e zellij "$@"
  fi
}

rofi_cmd() {
  MSG=$1
  rofi -dmenu -i -mesg "$MSG"
}
session_list() {
  zellij ls -s | tr ' ' '\n'
}

session_menu() {
  echo -e "$(session_list)" | rofi_cmd "Session:"
}

layout_menu() {
  layout_list=$(find ~/.config/zellij/layouts -name "*.kdl" | sed 's|.*/||; s/\.kdl$//' | tr ' ' '\n')
  echo -e "$layout_list" | rofi_cmd "Select layout for $session_name:"
}

session_select() {
  session_name=$(session_menu)
  if [[ -z "$session_name" ]]; then
    echo "Nothing selected."
    exit 0
  fi

  # Check if the session name exists in the session list
  if session_list | grep -qx "$session_name"; then
    session_action="select"
  else
    session_action="create"
  fi
}

selection_menu() {
  echo -e "Attach\nDelete\nBack" | rofi_cmd "$session_name action:"
}

main() {
  while true; do
    session_select

    case $session_action in
    "create")
      layout="$(layout_menu)"
      if [ -z "$layout" ]; then
        echo "no layout given"
        continue
      fi
      zellij_cmd -s "$session_name" --layout "$layout"
      break
      ;;
    "select")
      selection=$(selection_menu)
      case $selection in
      "Attach")
        zellij_cmd attach "$session_name"
        break
        ;;
      "Delete")
        zellij delete-session --force "$session_name"
        ;;
      "Back")
        echo "Going back."
        ;;
      *)
        echo "Going Back."
        ;;
      esac
      ;;
    *)
      echo "Going Back"
      ;;
    esac
  done
}

main
